### ISSUE TITLE
admin filter similar users

### ISSUE THREAD

**Issue by AdamGan** [CS2102-Grp23/Project#12]
suppose to show pairs of users per row, not single users

**Comment by ycewe** [comment]
You returned a single array with multiple objects. If you want a pair of users, you may need to change your return method to an array of array of objects. And what if 3 users have the similar contribution?

**Comment by AdamGan** [comment]
it's pairs of users, if 3 similar, it would be { {A,B}, {A,C}, {B,C} }

**Comment by ycewe** [comment]
So one row will show all 3 similar user? If got 4, do I fit all into one row as well?

If this is the case, you need to return an array of arrays. I cannot determine which users are in which group on the client side

**Comment by AdamGan** [comment]
it is an array of arrays, and it's pairs of users, there's no 3 record inner-array
