### ISSUE TITLE
admin filter Nation

### ISSUE THREAD

**Issue by AdamGan** [CS2102-Grp23/Project#13]
suppose to have 2, top nation by contributions and top nation by project count.
Only using contributions now, but display is empty

**Comment by ycewe** [comment]
When users register, nationality is not save. What I get back from search is null. Check authController

**Comment by AdamGan** [comment]
i think old database again, i changed some records to include nationality

**Comment by ycewe** [comment]
As in authController does retrieves and save nationality if I am not mistaken. If register as new user, their nationality is not saved.

**Comment by AdamGan** [comment]
signup:
$query = "INSERT INTO users VALUES('$userName', '$password', 'FALSE', '$email','$name')";
no nationality yet. 

But regardless, database entries should have been updated users with nationality which will return results for that. Did you run the sql file again?
