### ISSUE TITLE
admin manage project

### ISSUE THREAD

**Issue by AdamGan** [CS2102-Grp23/Project#14]
same as a normal user view, becomes contribution instead of edit

**Comment by ycewe** [comment]
Normal user view is contribute page

**Comment by AdamGan** [comment]
master branch: so admin's manage project is just like a normal user's contribute? not to edit project details?  
UI branch: can't access /admin to check

**Comment by ycewe** [comment]
Currently cannot edit project details at all. There is no route to edit project

**Comment by AdamGan** [comment]
thought Woo Jeong did it, nvm then scrap it
