### ISSUE TITLE
contribute route added

### ISSUE THREAD

**Issue by AdamGan** [CS2102-Grp23/Project#5]
Route::get('/user/contribute/{projectID}/{contribution}', 'projectController@contribute');

//returns "Please enter a valid contribution." OR 'SUCCESS', not a select statement

**Comment by AdamGan** [comment]
#4 <- couldn't see the single project page. Can't check contribute

**Comment by ycewe** [comment]
Change route to Route::post('/project/contribute', 'projectController@contribute');
